chats/urls.py
from django.urls import path
from . import views

app_name = 'chats'

urlpatterns = [
    path('', views.ChatsListView.as_view(), name='chats'),
    path('create_chat/<int:user_id>/',
         views.CreateOrRedirectChatView.as_view(), name='create_chat'),
    path('<int:pk>/', views.ChatDetailView.as_view(), name='chat_detail')
]

pop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
    path('chats/', include('chats.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('edit/', views.EditProfileView.as_view(), name='edit'),
    path('<str:username>/', views.ProfilePageView.as_view(), name='profile'),
    path('follow/<str:username>/', views.follow, name='follow'),
    path('<str:username>/<str:stat>/',
         views.FollowStatView.as_view(), name='follow_stat'),
]

chats/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Chat(models.Model):
    users = models.ManyToManyField(User, related_name='chats')
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Chat between {', '.join([user.username for user in self.users.all()])}"


class Message(models.Model):
    chat = models.ForeignKey(
        Chat, related_name='messages', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message from {self.user.username} in chat {self.chat.id}"

chats/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.views.generic import ListView, DetailView
from .models import Chat, User, Message

# Create your views here.


class ChatsListView(ListView):
    model = Chat
    template_name = 'chats/chats.html'
    context_object_name = 'chats'

    def get_queryset(self):
        return self.request.user.chats.all()


class CreateOrRedirectChatView(View):
    def post(self, request, user_id):
        target_user = get_object_or_404(User, pk=user_id)

        chat = Chat.objects.filter(users=request.user).filter(
            users=target_user).first()

        if chat:
            return redirect('chats:chat_detail', pk=chat.id)
        else:
            chat = Chat.objects.create()
            chat.users.add(request.user, target_user)
            chat.save()

            return redirect('chats:chat_detail', pk=chat.id)


class ChatDetailView(DetailView):
    model = Chat
    template_name = 'chats/chat_detail.html'

    def get_object(self):
        chat_id = self.kwargs.get('pk')
        return get_object_or_404(Chat, id=chat_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['messages'] = Message.objects.filter(
            chat=self.object).order_by('created_at')
        return context

chats/templates/chats/chat_detail.html
{% extends "core/base.html" %}

{% load static %}

{% block title %}Chat Detail{% endblock title %}

{% block content %}
<div class="p-3 bg-white rounded-lg shadow-lg h-max-2/3 space-y-4">
    {% for user in chat.users.all %}
        {% if user != request.user %}
            <a href="{% url "users:profile" user.username %}" class="flex items-center space-x-4 p-3">
                {% if user.user_profile and user.user_profile.profile_picture %}
                    <img class="border-2 w-10 h-10 rounded-full object-cover object-center aspect-square" src="{{ user.user_profile.profile_picture.url }}">
                {% else %}
                    <img class="border-2 w-10 h-10 rounded-full" src="{% static 'user2.png' %}">
                {% endif %}
                <div>
                    <p class="text-lg font-semibold">{{ user.username }}</p>
                    <p class="text-xs text-gray-500">{{ chat.modified_at }}</p>
                </div>
            </a>
        {% endif %}
    {% endfor %}

    <div id="chat-messages" class="chat-messages messages p-2 rounded-lg h-fit">
        {% for message in messages %}
        {% if message.user == request.user %}
        <div class="mb-3">
            <span class="text-gray-500 text-xs">{{ message.created_at|date:"F d, Y, h:i A" }}</span>
            <div class="flex border-2 border-gray-200 p-2 rounded-lg">
                {% if message.user.user_profile and message.user.user_profile.profile_picture %}
                <img class="border-2 w-10 h-10 rounded-full object-cover object-center aspect-square" src="{{ user.user_profile.profile_picture.url }}">
                {% else %}
                <img class="border-2 w-10 h-10 rounded-full" src="{% static 'user2.png' %}">
                {% endif %}
                <p class="ml-2 mt-2">{{ message.content }}</p>
            </div>
        </div>
        {% else %}
        <div class="mb-3">
            <span class="text-gray-500 text-xs">{{ message.created_at|date:"F d, Y, h:i A" }}</span>
            <div class="flex bg-gray-100 p-2 rounded-lg">
                {% if message.user.user_profile and message.user.user_profile.profile_picture %}
                    <img class="border-2 w-10 h-10 rounded-full object-cover object-center aspect-square" src="{{ message.user.user_profile.profile_picture.url }}">
                {% else %}
                    <img class="border-2 w-10 h-10 rounded-full" src="{% static 'user2.png' %}">
                {% endif %}
                <p class="ml-2 mt-2">{{ message.content }}</p>
            </div>
        </div>
        {% endif %}
        {% empty %}
            <p id="no-message" class="p-2 bg-gray-100 rounded-lg">No messages yet.</p>
        {% endfor %}
    </div>

    <form id="message-form" method="post" action="." class="flex items-center space-x-2 mt-2">
        {% csrf_token %}
        <input name="content" id="message-input" class="w-full rounded-lg p-2 focus:outline-none" placeholder="Type your message here..." required></input>
        <button type="submit" class="bg-yellow-400 text-white rounded-lg px-4 py-2 hover:bg-yellow-500">Send</button>
    </form>
</div>

<script>
    const chatId = "{{ chat.id }}";
    const chatSocket = new WebSocket(`ws://${window.location.host}/ws/chat/${chatId}/`);
    const currentUser = "{{ request.user.username }}";

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        const messageElement = document.createElement('div');
        const noMessageP = document.getElementById('no-message')
        const isCurrentUser = data.user.trim().toLowerCase() === currentUser.trim().toLowerCase();

        messageElement.className = 'mb-3';

        if (isCurrentUser) {
            messageElement.innerHTML = `
                <span class="text-gray-500 text-xs">${data.created_at}</span>
                <div class="flex border-2 border-gray-200 p-2 rounded-lg">
                    <img class="border-2 w-10 h-10 rounded-full object-cover object-center aspect-square" src="${data.profile_picture}">
                    <p class="ml-2 mt-2">${data.content}</p>
                </div>`;
        } else {
            messageElement.innerHTML = `
                <span class="text-gray-500 text-xs">${data.created_at}</span>
                <div class="flex bg-gray-100 p-2 rounded-lg">
                    <img class="border-2 w-10 h-10 rounded-full object-cover object-center aspect-square" src="${data.profile_picture}">
                    <p class="ml-2 mt-2">${data.content}</p>
                </div>`;
        }

            if (noMessageP) {
                noMessageP.remove();
            }
            
            document.getElementById('chat-messages').appendChild(messageElement);

            scrollToBottom();
        };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.getElementById('message-form').onsubmit = function(e) {
        e.preventDefault();
        const messageInputDom = document.getElementById('message-input');
        const message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'content': message
        }));
        messageInputDom.value = '';
    };

    function scrollToBottom() {
        let objDiv = document.getElementById("chat-messages");
        objDiv.scrollTop = objDiv.scrollHeight;
    }

    scrollToBottom();
</script>
{% endblock content %}

chats/templates/chats/chats.html
{% extends "core/base.html" %}

{% load static %}

{% block title %}Chats{% endblock title %}

{% block content %}
{% if chats %}
{% for chat in chats %}
<div class="bg-white rounded-lg shadow-lg mb-3 hover:bg-gray-200">
    <a href="{% url "chats:chat_detail" chat.id %}" class="flex items-center space-x-4 p-3">
        {% for user in chat.users.all %}
            {% if user != request.user %}
                {% if user.user_profile and user.user_profile.profile_picture %}
                    <img class="border-2 w-10 h-10 rounded-full object-cover object-center aspect-square" src="{{ user.user_profile.profile_picture.url }}">
                {% else %}
                    <img class="border-2 w-10 h-10 rounded-full" src="{% static 'user2.png' %}">
                {% endif %}
                <div>
                    <p class="text-lg font-semibold">{{ user.username }}</p>
                    <p class="text-xs text-gray-500">{{ chat.modified_at }}</p>
                </div>
            {% endif %}
        {% endfor %}
    </a>
</div>
{% endfor %}
    {% else %}
        <div class="bg-white rounded-lg shadow-lg p-3">
            <h1 class="p-3 text-center text-lg">You have no chats yet.</h1>
        </div>
    {% endif %}
{% endblock content %}