chats/urls.py
from django.urls import path
from . import views

app_name = 'chats'

urlpatterns = [
    path('', views.ChatsListView.as_view(), name='chats'),
    path('create_chat/<int:user_id>/',
         views.CreateOrRedirectChatView.as_view(), name='create_chat'),
    path('<int:pk>/', views.ChatDetailView.as_view(), name='chat_detail')
]

core/urls.py
from django.urls import path
from . import views
from .views import CustomLoginView, custom_logout
from django.contrib.auth import views as auth_views

app_name = 'core'

urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', custom_logout, name='logout'),
]

pop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
    path('chats/', include('chats.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('new/', views.NewPostView.as_view(), name='new'),
    path('like/<int:pk>/<str:redirection>/', views.like, name='like'),
    path('delete_comment/<int:post_pk>/<int:comment_pk>/<str:redirection>/',
         views.DeleteCommentView.as_view(), name='delete_comment'),
    path('explore/', views.ExplorePageView.as_view(), name='explore'),
    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('saved/', views.SavedPageView.as_view(), name='saved'),
    path('save/<int:pk>/<str:redirection>/', views.save, name='save'),
    path('delete/<int:pk>/', views.DeletePostView.as_view(), name='delete_post')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('edit/', views.EditProfileView.as_view(), name='edit'),
    path('<str:username>/', views.ProfilePageView.as_view(), name='profile'),
    path('follow/<str:username>/', views.follow, name='follow'),
    path('<str:username>/<str:stat>/',
         views.FollowStatView.as_view(), name='follow_stat'),
]

core/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Post(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='posts')
    content = models.TextField()
    image = models.ImageField(upload_to='post_images/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Post by {self.author.username} at {self.created_at}"


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='likes')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'post')

    def __str__(self):
        return f"{self.user.username} liked {self.post.id}"


class Comment(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='comment_author')
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comment')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.author.username} commented on post: {self.post.id}, at: {self.created_at}"

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

CLASSES = 'w-full py-4 px-6 rounded-xl border-2'


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': CLASSES
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Email address',
        'class': CLASSES
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': CLASSES
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': CLASSES
    }))


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': CLASSES
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': CLASSES
    }))

posts/forms.py
from django import forms
from .models import Post, Comment


class NewPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content', 'image']

    content = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Write your description here',
        'class': 'w-full py-4 px-6 rounded-xl border-2',
        'rows': 5
    }))

    image = forms.ImageField(widget=forms.ClearableFileInput(attrs={
        'class': 'hidden'
    }))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

    content = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Add a comment...',
        'class': 'p-2 w-full h-11 rounded-lg focus:outline-none',
        'rows': 1,
        'style': 'resize: none;'
    }))

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.contrib.auth.views import LoginView
from django.views.generic import ListView, FormView
from django.db.models import Subquery, OuterRef, Exists
from posts.models import Post, Like, Comment
from users.models import Profile, Follow
from posts.forms import CommentForm
from .forms import SignUpForm, LoginForm


class PostListView(ListView):
    model = Post
    template_name = 'core/index.html'
    context_object_name = 'posts'
    ordering = ['-created_at']

    def get_queryset(self):
        if self.request.user.is_authenticated:
            following = Follow.objects.filter(
                follower=self.request.user).values('following')
            posts = Post.objects.filter(author__in=Subquery(
                following)).order_by('-created_at')

            user_liked = Like.objects.filter(
                user=self.request.user, post=OuterRef('pk'))
            posts = posts.annotate(user_liked=Exists(user_liked))

            return posts
        return Post.objects.none()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['comment_form'] = CommentForm()
            context['comments'] = Comment.objects.select_related(
                'author').filter(post__in=context['posts'])
            profile = self.request.user.user_profile
            context["saved_posts"] = profile.saved_posts.all()
        return context

    def get_template_names(self):
        if not self.request.user.is_authenticated:
            return ['core/welcome.html']
        return [self.template_name]

    def post(self, request, *args, **kwargs):
        if request.method == 'POST' and request.user.is_authenticated:
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                new_comment = comment_form.save(commit=False)
                new_comment.author = request.user
                post_id = request.POST.get('post_id')
                new_comment.post = Post.objects.get(id=post_id)
                new_comment.save()

                return HttpResponseRedirect(reverse('core:index'))

            return self.get(request, *args, **kwargs)


class SignUpView(FormView):
    template_name = 'core/signup.html'
    form_class = SignUpForm
    success_url = reverse_lazy('core:index')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.username = user.username.lower()
        user.save()

        Profile.objects.create(user=user)

        login(self.request, user)

        return super().form_valid(form)


class CustomLoginView(LoginView):
    form_class = LoginForm
    template_name = 'core/login.html'

    def get_success_url(self):
        return reverse_lazy('core:index')


@login_required
def custom_logout(request):
    logout(request)
    return redirect('core:index')

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView
from django.views.generic import CreateView
from django.views.generic.edit import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Count
from .forms import NewPostForm
from .forms import CommentForm
from .models import Post, Like, Comment


class NewPostView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = NewPostForm
    template_name = 'posts/new.html'
    success_url = reverse_lazy('core:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


@login_required
def like(request, pk, redirection):
    post_to_like = get_object_or_404(Post, pk=pk)

    like_instance, created = Like.objects.get_or_create(
        user=request.user,
        post=post_to_like
    )

    if not created:
        like_instance.delete()

    if redirection == 'detail':
        return redirect('posts:detail', pk=pk)
    elif redirection == 'profile':
        return redirect('users:profile', username=post_to_like.author.username)
    else:
        return redirect('core:index')


class DeleteCommentView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    success_url = 'core:index'

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        comment_pk = self.kwargs.get('comment_pk')
        self.object = Comment.objects.get(pk=comment_pk)
        self.object.delete()

        redirection = self.kwargs.get('redirection')
        post_pk = self.kwargs.get('post_pk')

        if redirection == 'detail':
            return redirect('posts:detail', pk=post_pk)
        elif redirection == 'profile':
            post = get_object_or_404(Post, pk=post_pk)
            return redirect('users:profile', username=post.author.username)
        else:
            return redirect(self.get_success_url())

    def test_func(self):
        comment_pk = self.kwargs.get('comment_pk')
        comment = Comment.objects.get(pk=comment_pk)
        return self.request.user == comment.author


class ExplorePageView(ListView):
    model = Post
    template_name = 'posts/explore.html'
    context_object_name = 'posts'

    def get_queryset(self):
        last_1000_posts = Post.objects.annotate(
            like_count=Count('likes')).order_by('-created_at')[:1000]

        last_1000_posts_list = list(last_1000_posts)

        average_like_count = sum(post.like_count for post in last_1000_posts_list) / \
            len(last_1000_posts_list) if last_1000_posts_list else 0

        filtered_posts = [
            post for post in last_1000_posts_list if post.like_count >= average_like_count]

        search_query = self.request.GET.get('explore', '').strip()

        if search_query:
            filtered_posts = [
                post for post in filtered_posts if search_query.lower() in post.content.lower() or search_query.lower() in post.author.username.lower()]

        return filtered_posts

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Explore'
        return context


class PostDetailView(DetailView):
    model = Post
    template_name = 'posts/post_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        post = self.get_object()

        if self.request.user.is_authenticated:
            context['comment_form'] = CommentForm()
            context['comments'] = Comment.objects.select_related(
                'author').filter(post=post)
            profile = self.request.user.user_profile
            context["saved_posts"] = profile.saved_posts.all()

        if self.request.user.is_authenticated:
            context['user_liked'] = Like.objects.filter(
                post=post, user=self.request.user).exists()

        return context

    def post(self, request, *args, **kwargs):
        post = self.get_object()
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            new_comment.save()

        return redirect(reverse('posts:detail', kwargs={'pk': post.id}))


class SavedPageView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'posts/explore.html'
    context_object_name = 'posts'

    def get_queryset(self):
        profile = self.request.user.user_profile
        saved_posts = profile.saved_posts.all()
        return saved_posts

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Saved'
        return context


@login_required
def save(request, pk, redirection):
    post_to_save = get_object_or_404(Post, pk=pk)
    profile = request.user.user_profile

    if post_to_save in profile.saved_posts.all():
        profile.saved_posts.remove(post_to_save)
    else:
        profile.saved_posts.add(post_to_save)

    if redirection == 'detail':
        return redirect('posts:detail', pk=pk)
    elif redirection == 'profile':
        return redirect('users:profile', username=post_to_save.author.username)
    else:
        return redirect('core:index')


class DeletePostView(LoginRequiredMixin, DeleteView):
    model = Post

    def get_success_url(self):
        username = self.object.author.username
        return reverse('users:profile', kwargs={'username': username})

core/templates/core/authform.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | POP</title>
    {% comment %} <script src="https://cdn.tailwindcss.com"></script> {% endcomment %}
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
    <link rel="stylesheet" href="{% static 'core/css/font.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
</head>
<body class="bg-gray-100">
    <nav class="py-6 px-52 flex justify-between items-center h-14 shadow-lg z-10 relative bg-white">
        <div>
            <a href="/">
                <div class="flex items-center space-x-3">
                    <img class="h-8" src="{% static "logo.png" %}">
                    <h1 class="text-2xl font-bold">POP</h1>
                </div>
            </a>
        </div>
    </nav>

    <div class="mt-12 flex justify-center">
        {% block content %}
        
        {% endblock content %}
    </div>
</body>
</html>

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %} | POP</title>
    {% comment %} <script src="https://cdn.tailwindcss.com"></script> {% endcomment %}
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
    <link rel="stylesheet" href="{% static 'core/css/font.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <style>
        .chat-messages {
            height: 400px;
            overflow-y: auto
        }

        .content {
            max-width: 600px;
        }
    </style>
</head>
<body class="bg-gray-100">
    <nav class="py-6 px-52 flex justify-between items-center h-14 shadow-lg z-10 z-40 fixed top-0 w-full bg-white">
        <div class="relative flex items-center space-x-4">
            <a href="/">
                <div class="flex items-center space-x-1">
                    <img class="h-9" src="{% static "logo.png" %}">
                    <h1 class="text-3xl font-bold">POP</h1>
                </div>
            </a>
            <ul>
                <li class="px-2 bg-gray-200 rounded-full text-md font-normal text-gray-500 {% if request.path == '/' %}active {% else %} hidden {% endif %}">HOME</li>
                <li class="px-2 bg-gray-200 rounded-full text-md font-normal text-gray-500 {% if request.path == '/posts/explore/' %}active {% else %} hidden {% endif %}">EXPLORE</li>
                <li class="px-2 bg-gray-200 rounded-full text-md font-normal text-gray-500 {% if request.path == '/posts/saved/' %}active {% else %} hidden {% endif %}">SAVED</li>
                <li class="px-2 bg-gray-200 rounded-full text-md font-normal text-gray-500 {% if request.path == '/chats/' %}active {% else %} hidden {% endif %}">CHATS</li>
                <li class="px-2 bg-gray-200 rounded-full text-md font-normal text-gray-500 {% if request.path == '/posts/new/' %}active {% else %} hidden {% endif %}">NEW</li>
            </ul>
        </div>

        {% comment %} search {% endcomment %}

        <div class="flex space-x-3">
        {% if request.user.is_authenticated %}
        <div class="flex items-center">
            <div class="flex items-center mr-3 border-2 border-gray-200 rounded-full hover:bg-gray-200">
                <a href="{% url "users:profile" user.username %}" class="flex items-center">
                    <div class="ml-2">
                        <p class="text-lg mr-2">{{ user.username }}</p>
                    </div>
                    {% if user.user_profile and user.user_profile.profile_picture %}
                        <div class="w-9 h-9 rounded-full overflow-hidden border-2 border-gray-200 clip-half">
                            <img class="w-full h-full object-cover object-center aspect-square" src="{{ user.user_profile.profile_picture.url }}">
                        </div>
                    {% else %}
                        <div class="w-9 h-9 rounded-full overflow-hidden border-2 border-gray-200">
                            <img class="w-full h-full object-cover object-center aspect-square" src="{% static "user2.png" %}">
                        </div>
                    {% endif %}
                </a>
            </div>
            <a href="{% url "core:logout" %}" class="px-4 py-1 bg-yellow-400 rounded-full hover:bg-yellow-500">
                <h2 class="font-medium text-lg text-white">Logout</h2>
            </a>
        </div>
        {% else %}
            <a href="{% url "core:signup" %}" class="px-3 py-1 hover:text-yellow-400">
                <h2 class="font-medium text-lg">Sign Up</h2>
            </a>
            <a href="{% url "core:login" %}" class="px-4 py-1 bg-yellow-400 rounded-full hover:bg-yellow-500">
                <h2 class="font-medium text-lg text-white">Login</h2>
            </a>
        {% endif %}
        </div>
    </nav>

        {% if request.user.is_authenticated %}
        <div class="w-52 shadow-lg rounded-lg px-3 py-3 space-y-3 h-fit bg-white fixed top-20 left-52">
            <a href="{% url "core:index" %}" class="p-2 rounded-lg hover:bg-gray-200 block">
                <div class="flex items-center space-x-3">
                    <img class="h-5" src="{% static "home2.png" %}">
                    <h2 class="text-xl">Home</h1>
                </div>
            </a>
            <a href="{% url "posts:explore" %}" class="p-2 rounded-lg hover:bg-gray-200 block">
                <div class="flex items-center space-x-3">
                    <img class="h-5" src="{% static "search2.png" %}">
                    <h2 class="text-xl">Explore</h1>
                </div>
            </a>
            <a href="{% url "posts:saved" %}" class="p-2 rounded-lg hover:bg-gray-200 block">
                <div class="flex items-center space-x-3">
                    <img class="h-5" src="{% static "save.png" %}">
                    <h2 class="text-xl">Saved</h1>
                </div>
            </a>
            <a href="{% url "chats:chats" %}" class="p-2 rounded-lg hover:bg-gray-200 block">
                <div class="flex items-center space-x-3">
                    <img class="h-5" src="{% static "comment2.png" %}">
                    <h2 class="text-xl">Chats</h1>
                </div>
            </a>
            <a href="{% url "posts:new" %}" class="p-2 rounded-lg shadow-lg bg-yellow-400 text-white hover:bg-yellow-500 text-center block">
                    <p class="font-medium text-xl">New Post</p>
            </a>
        </div>
        {% endif %}

        <button id="scrollToTopBtn" class="fixed bottom-8 right-52 w-12 h-12 hidden bg-yellow-400 text-white rounded-full p-3 shadow-lg hover:bg-yellow-500 transition-all duration-300">
            ↑
        </button>
    
        <script>
            const scrollToTopBtn = document.getElementById("scrollToTopBtn");
    
            window.onscroll = function() {
                if (document.body.scrollTop > 100 || document.documentElement.scrollTop > 100) {
                    scrollToTopBtn.classList.remove("hidden");
                } else {
                    scrollToTopBtn.classList.add("hidden");
                }
            };
    
            scrollToTopBtn.addEventListener("click", function() {
                window.scrollTo({
                    top: 0,
                    behavior: "smooth"
                });
            });
        </script>
    
                
    <div class="px-36 py-20 flex justify-center">
        <div class="content w-1/2">
            {% block content %}
            
            {% endblock content %}
        </div>
    </div>
</body>
</html>

core/templates/core/index.html
{% extends "core/base.html" %}

{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
    {% if posts %}
    {% for post in posts %}
        {% include "core/post.html" with post=post redirection='index' saved_posts=saved_posts%}
    {% endfor %}
    {% else %}
    <div class="px-6 py-4 shadow-lg rounded-lg bg-white">
        <h1 class="pb-4 text-2xl font-bold mb-6 border-b-2 border-gray-200">There are no posts for you to see yet</h1>
        <div class="text-lg space-y-6">
            <p>Follow users to see their posts</p>
            <p>Look up our <a class="font-semibold hover:text-yellow-400" href="#">Explore</a> page to see the hottest posts on our site</p>
            <p>Search for posts you'd like to see</p>
        </div>
    </div>
    {% endif %}
{% endblock %}

core/templates/core/login.html
{% extends "core/authform.html" %}

{% block title %}Login{% endblock title %}

{% block content %}
<div class="w-1/3 rounded-lg bg-white px-6 py-3 shadow-lg">
    <h2 class="mb-6 text-xl font-semibold">Login</h2>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            {{ form.username }}
        </div>

        <div class="mb-3">
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <div class="w-full mb-3 mt-6 flex justify-center">
            <h2 class="font-semibold mr-2">Don't have an account yet?</h2>
            <a href="{% url "core:signup" %}" class="font-bold text-yellow-400 hover:text-yellow-500">Sign up</a>
        </div>

        <button class="w-full mt-3 mb-3 px-4 py-1 text-lg bg-yellow-400 hover:bg-yellow-500 shadow-lg rounded-lg text-white font-semibold">Login</button>
</div>
{% endblock content %}

core/templates/core/signup.html
{% extends "core/authform.html" %}

{% block title %}Sign up{% endblock title %}

{% block content %}
<div class="w-1/3 rounded-lg bg-white px-6 py-3 shadow-lg">
    <h2 class="mb-6 text-xl font-semibold">Sign up</h2>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            {{ form.username }}
        </div>

        <div class="mb-3">
            {{ form.email }}
        </div>

        <div class="mb-3">
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <div class="w-full mb-3 mt-6 flex justify-center">
            <h2 class="font-semibold mr-2">Already have an account?</h2>
            <a href="{% url "core:login" %}" class="font-bold text-yellow-400 hover:text-yellow-500">Login</a>
        </div>

        <button class="w-full mt-3 mb-3 px-4 py-1 text-lg bg-yellow-400 hover:bg-yellow-500 shadow-lg rounded-lg text-white font-semibold">Sign up</button>
</div>
{% endblock content %}

core/templates/core/welcome.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Welcome{% endblock title %}

{% block content %}
<div class="px-12 py-8 my-12 rounded-lg bg-white shadow-lg mt-24">
    <div class="flex border-b-2 pb-6">
        <h1 class="text-xl">Welcome to </h1>
        <div class="flex items-center">
            <img class="ml-3 mr-1 h-8" src="{% static "logo.png" %}">
            <h1 class="text-xl font-bold">POP</h1>
        </div>
    </div>
    <div class="flex mt-6">
        <p class="text-lg">
            To use the website to it's full extent
        </p>
        <a href="{% url "core:signup" %}" class="mx-2 text-xl font-bold hover:text-yellow-400">Sign up</a>
        <p class="text-lg">or</p>
        <a href="{% url "core:login" %}" class="ml-2 text-xl font-bold hover:text-yellow-400">Login</a>
    </div>
    <p class="text-xl font-bold mt-6">OR</p>
    <div class="flex mt-6">
        <p class="text-lg">
            Visit our
        </p>
        <a href="{% url "posts:explore" %}" class="mx-2 text-xl font-bold hover:text-yellow-400">Explore</a>
        <p class="text-lg">page</p>
    </div>
</div>
{% endblock content %}