chats/urls.py
from django.urls import path
from . import views

app_name = 'chats'

urlpatterns = [
    path('', views.ChatsListView.as_view(), name='chats'),
    path('create_chat/<int:user_id>/',
         views.CreateOrRedirectChatView.as_view(), name='create_chat'),
    path('<int:pk>/', views.ChatDetailView.as_view(), name='chat_detail')
]

pop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
    path('chats/', include('chats.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('edit/', views.EditProfileView.as_view(), name='edit'),
    path('<str:username>/', views.ProfilePageView.as_view(), name='profile'),
    path('follow/<str:username>/', views.follow, name='follow'),
    path('<str:username>/<str:stat>/',
         views.FollowStatView.as_view(), name='follow_stat'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from posts.models import Post

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='user_profile')
    bio = models.TextField(blank=True)
    profile_picture = models.ImageField(
        upload_to='profile_pictures/', null=True)
    saved_posts = models.ManyToManyField(
        Post, blank=True, related_name='saved_by')

    def __str__(self):
        return self.user.username


class Follow(models.Model):
    follower = models.ForeignKey(
        User, related_name='following', on_delete=models.CASCADE)
    following = models.ForeignKey(
        User, related_name='followers', on_delete=models.CASCADE)

    class Meta:
        unique_together = ('follower', 'following')
        verbose_name = 'Follow'
        verbose_name_plural = 'Follows'

    def __str__(self):
        return f'{self.follower.username} follows {self.following.username}'

users/forms.py
from django import forms
from .models import Profile


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'profile_picture']

    bio = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={
            'placeholder': 'Bio',
            'class': 'w-full py-4 px-6 rounded-xl border-2',
            'rows': 5
        }))

    profile_picture = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(attrs={
            'class': 'hidden'
        }))

users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import OuterRef, Exists
from .models import Profile, Follow
from .forms import EditProfileForm
from posts.models import Post, Like, Comment
from posts.forms import CommentForm


class ProfilePageView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'users/profile.html'
    context_object_name = 'profile'
    slug_field = 'user__username'
    slug_url_kwarg = 'username'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object.user
        posts = Post.objects.filter(
            author=user).order_by('-created_at')

        user_liked = Like.objects.filter(
            user=self.request.user, post=OuterRef('pk'))
        posts = posts.annotate(user_liked=Exists(user_liked))

        context['posts'] = posts

        context['is_following'] = Follow.objects.filter(
            follower=self.request.user, following=user
        ).exists()

        profile = self.request.user.user_profile
        context["saved_posts"] = profile.saved_posts.all()

        if self.request.user.is_authenticated:
            context['comment_form'] = CommentForm()
            context['comments'] = Comment.objects.select_related(
                'author').filter(post__in=context['posts'])
            profile = self.request.user.user_profile

        return context

    def post(self, request, *args, **kwargs):
        if request.method == 'POST' and request.user.is_authenticated:

            comment_form = CommentForm(request.POST)

            if comment_form.is_valid():
                new_comment = comment_form.save(commit=False)
                new_comment.author = request.user
                post_id = request.POST.get('post_id')
                new_comment.post = Post.objects.get(id=post_id)
                new_comment.save()

                return redirect('users:profile', username=self.get_object().user.username)

            return self.get(request, *args, **kwargs)


class EditProfileView(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = EditProfileForm
    template_name = 'users/edit_profile.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Profile, user=self.request.user)

    def get_success_url(self):
        return reverse_lazy('users:profile', kwargs={'username': self.request.user.username})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = self.get_object()
        return context


@login_required
def follow(request, username):
    user_to_follow = get_object_or_404(User, username=username)
    current_user = get_object_or_404(User, username=request.user.username)

    if current_user == user_to_follow:
        return redirect('users:profile', username)

    follow_instance, created = Follow.objects.get_or_create(
        follower=current_user,
        following=user_to_follow
    )

    if not created:
        follow_instance.delete()

    return redirect('users:profile', username=username)


class FollowStatView(ListView):
    template_name = 'users/follow_stat.html'
    context_object_name = 'users'

    def get_queryset(self):
        self.user = get_object_or_404(User, username=self.kwargs['username'])
        self.profile = get_object_or_404(Profile, user=self.user)
        stat = self.kwargs['stat']

        if stat == 'followers':
            users_list = Follow.objects.filter(
                following=self.user).select_related('follower')
            return [follow.follower for follow in users_list]
        elif stat == 'following':
            users_list = Follow.objects.filter(
                follower=self.user).select_related('following')
            return [follow.following for follow in users_list]
        else:
            return []

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = self.profile
        context['stat'] = self.kwargs['stat']
        return context

users/templates/users/edit_profile.html
{% extends "core/base.html" %}

{% block title %}Edit Profile{% endblock title %}

{% block content %}
    <div class="rounded-lg bg-white px-6 py-3 shadow-lg">
        <h2 class="mb-6 text-xl font-semibold">Edit Profile</h2>

        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="mb-3">
                {{ form.bio }}
            </div>
    
            <div class="mb-3">
                <div class="flex items-center justify-between w-full py-3">
                    <div>
                        <label class="cursor-pointer block">
                            <span class="text-md text-gray-400 bg-white px-6 py-2 border-2 rounded-lg hover:bg-gray-200">
                                Choose Image
                            </span>
                            <!-- Ensure the input is visible but styled to be hidden -->
                            <input type="file" name="profile_picture" class="hidden" onchange="updateFileName(this)">
                        </label>
                    </div>
                    <span id="file-chosen" class="text-sm text-gray-500 ml-2">No file chosen</span>
                </div>
            </div>

            <script>
                function updateFileName(input) {
                    const fileChosen = document.getElementById('file-chosen');
                    if (input.files.length > 0) {
                        fileChosen.textContent = input.files[0].name;
                    } else {
                        fileChosen.textContent = 'No file chosen';
                    }
                }
            </script>
    
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
                
            <div class="flex space-x-3">
                <a class="w-full mt-3 mb-3 px-4 py-1 text-lg bg-gray-300 hover:bg-gray-400 shadow-lg rounded-lg text-white font-medium text-center" href="{% url 'users:profile' profile.user.username %}">Cancel</a>
                <button class="w-full mt-3 mb-3 px-4 py-1 text-lg bg-yellow-400 hover:bg-yellow-500 shadow-lg rounded-lg text-white font-medium">Done</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/follow_stat.html
{% extends 'core/base.html' %}

{% load static %}
    
{% block title %}{{ stat|title }}{% endblock title %}

{% block content %}
<div class="rounded-lg bg-white px-6 py-3 shadow-lg">
    <div class="flex items-center">
        <a href="{% url "users:profile" profile.user.username %}">
            <h2 class="text-2xl font-bold">{{ profile.user.username }}</h2>
        </a>
        <p class="text-2xl">'s {{ stat }}</p>
    </div>
    <ul class="list-none mt-4">
        {% for user in users %}
        <a href="{% url 'users:profile' user.username %}">
            <li class="flex items-center px-2 py-2 border-2 mb-2 rounded-lg hover:bg-gray-200">
                {% if user.user_profile.profile_picture %}
                    <img src="{{ user.user_profile.profile_picture.url }}" class="border-2 border-gray-300 w-10 h-10 rounded-full">
                {% else %}
                    <img src="{% static "user2.png" %}" class="border-2 border-gray-300 w-10 h-10 rounded-full">
                {% endif %}
                <p class="ml-2">{{ user.username }}</p>
            </li>
        </a>
        {% empty %}
        <li>No {{ stat }} found.</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends "core/base.html" %}

{% load static %}

{% block title %}Profile{% endblock title %}

{% block content %}
    <div class="px-6 py-6 mb-6 flex justify-center rounded-lg shadow-lg bg-white">
        <div class="flex flex-col items-center">
            {% if profile.profile_picture %}
                <div class="w-96 h-96 mb-4 rounded-full overflow-hidden border-4 border-gray-200">
                    <img class="w-full h-full object-cover object-center aspect-square" src="{{ profile.profile_picture.url }}">
                </div>
            {% else %}
                <div class="w-96 h-96 mb-4 rounded-full overflow-hidden border-4 border-gray-200">
                    <img class="w-full h-full object-cover object-center aspect-square" src="{% static "user2.png" %}">
                </div>
            {% endif %}
            <h2 class="mb-4 text-lg">
                {{ profile.user.username }}
            </h2>
            <div class="flex space-x-3">
                <a href="{% url "users:follow_stat" profile.user.username 'followers' %}" class="px-4 py-1 bg-gray-200 rounded-full hover:bg-gray-300">Followers ({{ profile.user.followers.count }})</a>
                <a href="{% url "users:follow_stat" profile.user.username 'following' %}" class="px-4 py-1 bg-gray-200 rounded-full hover:bg-gray-300">Following ({{ profile.user.following.count }})</a>
                {% if not request.user == profile.user %}
                <form method="post" action="{% url 'users:follow' profile.user.username %}">
                    {% csrf_token %}
                    {% if is_following %}
                        <button type="submit" class="flex px-4 py-1 rounded-full bg-yellow-400 hover:bg-yellow-500 flex items-center space-x-2">
                            <p class="text-white font-medium">Following</p>
                            <img class="h-4" src="{% static "tick.png" %}">
                        </button>
                    {% else %}
                        <button type="submit" class="px-4 py-1 rounded-full bg-yellow-400 hover:bg-yellow-500">
                            <p class="text-white font-medium">Follow</p>
                        </button>
                    {% endif %}
                </form>
                <form action="{% url 'chats:create_chat' profile.user.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="flex items-center space-x-2 px-4 py-1 rounded-full bg-yellow-400 hover:bg-yellow-500">
                        <p class="text-white font-medium">Message</p>
                        <img class="h-4" src="{% static "chat3white.png" %}">
                    </button>
                </form>
                {% else %}
                <a href="{% url "users:edit" %}" class="px-4 py-1 bg-yellow-400 rounded-full bg-yellow-400 hover:bg-yellow-500">
                    <p class="text-white font-medium">Edit Profile</p>
                </a>
                {% endif %}
            </div>    
        </div>
    </div>

    {% if profile.bio %}
    <div class="px-6 py-6 mb-6 rounded-lg shadow-lg bg-white">
        <h2 class="text-gray-400">Bio</h2>
        <p>{{ profile.bio }}</p>
    </div>
    {% endif %}

    {% if posts %}
    {% for post in posts %}
        {% include "core/post.html" with post=post redirection='profile' saved_posts=saved_posts %}
    {% endfor %}
    {% else %}
        <div class="px-6 py-6 mb-6 rounded-lg shadow-lg bg-white">
            <h2>No posts yet</h2>
        </div>
    {% endif %}
{% endblock content %}